# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 09:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('image_name', models.CharField(max_length=200)),
                ('image_description', models.TextField(max_length=600)),
                ('image_location', models.CharField(max_length=200)),
                ('image_category', models.CharField(max_length=200)),
            ],
        ),
    ]
