# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-08 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pic', '0002_category_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image_link',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
